### ISSUE TITLE
Lists

### ISSUE THREAD

**Issue by machua416** [dandraka/XmlUtilities#1]
This is really not an issue but more of a question.

The second sample you used for the bug from the latest release that supposed to work, I tried accessing the HouseNumbers list and was not able to.

<?xml version="1.0" encoding="utf-8" ?>
<City>
  <Name>Wilen bei Wollerau</Name>
  <Gemeinde>Freienbach</Gemeinde>
  <Street name="Wolleraustrasse" />
  <Street name="Hungerstrasse" />
  <Street name="Rebmattli">
    <PostCode>8832</PostCode>
    <HouseNumbers>
      <HouseNumber>10</HouseNumber>
      <HouseNumber>12</HouseNumber>
      <HouseNumber>14</HouseNumber>
    </HouseNumbers>
  </Street>
</City>

How do you access the HouseNumber?  This is what I tried:
City.StreetList[2].HouseNumbers.HouseNumberList[0]
This gives me out of range error.  If I do, City.StreetList[2].HouseNumbers.HouseNumberList, it gives me a count of 0.

**Comment by dandraka** [comment]
Good morning!

I'll take a look in the evening. 

Jim

**Comment by dandraka** [comment]
Hmmm I think you found a bug :-)

**Comment by dandraka** [comment]
I got it fixed :-) It was really an issue in the tree walking algorithm, now it’s doing proper recursion. Plus I got it working not just with strings but with integers and booleans as well. 

I’ll finish testing tomorrow and then I’ll commit and create a new version. Thank you for your patience :-)

Jim

**Comment by dandraka** [comment]
New release 1.2 published here, also new nuget package 1.2.0 (https://www.nuget.org/packages/Dandraka.XmlUtilities/1.2.0).

@machua416 I've tested it thoroughly but would be happy if you could verify that it's working for your scenario.

Jim
