### ISSUE TITLE
"Type System.Xml.XmlCDataSection is not supported"

### ISSUE THREAD

**Issue by stefanoricci** [dandraka/XmlUtilities#2]
Is there any plan to support CData?
thanks!

**Comment by dandraka** [comment]
Hi! Hadn't thought of that to be honest. It's a good addition and a good opportunity as well -I have time now during the holidays, so I'll get to it in the next few days.

Do you have an example xml for me to test? (no personal/commercial data please).

**Comment by stefanoricci** [comment]
Hi!
glad to hear that you consider this a good opportunity

here's a sample

<CustomAttributes>
    <Attribute Name="document.id"><![CDATA[<string>DOCUMENTO N. 1234-9876</string>]]></Attribute>
    <Attribute Name="device.id"><![CDATA[<string>XYZ123</string>]]></Attribute>
    <Attribute Name="report.nr"><![CDATA[<string>278</string>]]></Attribute>
    <Attribute Name="receipt.nr"><![CDATA[<string>43</string>]]></Attribute>
    <Attribute Name="receipt.date"><![CDATA[<string>2020-12-28</string>]]></Attribute>
    <Attribute Name="fcurrency">EUR</Attribute>
</CustomAttributes>

thanks!

**Comment by dandraka** [comment]
Just published version 1.3.0 which solves this issue (XmlCDataSection not supported) and another one that I found by happy accident (XmlComment not supported).

Nuget package (recommended): https://www.nuget.org/packages/Dandraka.XmlUtilities/
Release (WARNING debug binaries!): https://github.com/dandraka/XmlUtilities/releases/tag/v1.3.0

Many thanks @stefanoricci ! Would be happy to hear your feedback.

Kind regards,

Jim

**Comment by stefanoricci** [comment]
Thank you @dandraka!
it works perfectly 🥇 


Stefano
